invoice_system/urls.py
# invoice_system/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('track_delivery/', include('track_delivery.urls')),
    path('send_emails/', include('invoicing.urls')),

]

invoicing/urls.py
from django.urls import path
from . import views

app_name = 'invoicing'

urlpatterns = [
    path('', views.render_upload_excel, name='render_upload_excel'),  # View to render the HTML form
    path('process_excel/', views.process_excel, name='process_excel'),  # View to process the form and send PDFs
]

track_delivery/urls.py
from django.urls import path
from . import views

app_name = 'track_delivery'

urlpatterns = [
    path('', views.track_deliveries, name='track_deliveries'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Choose Your App</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5 text-center">
        <h1>Welcome</h1>

        <!-- <div class="mt-4">
            <a href="{% url 'invoicing:render_upload_excel' %}" class="btn btn-primary btn-lg">Invoicing App</a>
        </div> -->
        <div class="mt-4">
            <a href="{% url 'track_delivery:track_deliveries' %}" class="btn btn-secondary btn-lg">Track Delivery App</a>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
</body>
</html>